### ISSUE TITLE
Publish latest version to PyPi?

### ISSUE THREAD

**Issue by camallen** [mwalmsley/zoobot#18]
A question rather than a request. Are there any plans to publish the refactored work ?

PyPi shows v0.0.1 is published https://pypi.org/project/zoobot/#history on 15th March 2021 but the latest code is ~v0.0.3 (tags) and the refactor seems to be working well.

Ideally I can pull in these packages to my own env / container and then train with the latest code vs pulling in from github etc.

**Comment by camallen** [comment]
marvelous - i will try out the package install

**Comment by mwalmsley** [comment]
Pleasure. I will now be keeping the main branch synced on pypi (I wonder if
there's an auto-release feature/action linking github release and pypi?)

**Comment by camallen** [comment]
this is working great by the way 👏🏼 

I've now got an isolated way to build the `zoobot-batch` image i'm using to run the zoobot training & prediction code, e.g. https://github.com/zooniverse/bajor/tree/main/azure/batch#zoobot-training-batch-processing-api-developer-readme
