### ISSUE TITLE
setup branch protection rules on 'main'

### ISSUE THREAD

**Issue by camallen** [mwalmsley/zoobot#36]
https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/defining-the-mergeability-of-pull-requests/managing-a-branch-protection-rule

It may be too restrictive for your use case / dev flows but we use this for contributor PRs etc. Basically we ensure that a PR meets certain criteria in terms of our CI runs, can only merge a PR once one of the CI runs v3.7 or v3.9 tests pass. 

Feel free to close if you don't think this is useful.

**Comment by camallen** [comment]
oh - combining the CI system with depenabot for auto package upgrades can be super useful. both for security alerts but also general package maintenance, https://docs.github.com/en/code-security/dependabot and https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuring-dependabot-version-updates

**Comment by mwalmsley** [comment]
I think that the Actions you helped set up provide a pretty good visual check on each PR that they succeed (at least, that they install and run the very minimal test). Probably this is not a priority right now, but we can revisit if we share merge access more widely.
