### ISSUE TITLE
Readme links are broken

### ISSUE THREAD

**Issue by mwalmsley** [mwalmsley/zoobot#42]
Review each link making sure they work.
Relies on docs building correctly

**Comment by BSGalvan** [comment]
We should be able to use [`sphinx-build`'s linkcheck option](https://www.sphinx-doc.org/en/master/man/sphinx-build.html#cmdoption-sphinx-build-b) to do this slightly more easily.

**Comment by mwalmsley** [comment]
Neat! linkcheck passes. Thanks for the tip.
