### ISSUE TITLE
upgrade galaxy-datasets?

### ISSUE THREAD

**Issue by camallen** [mwalmsley/zoobot#74]
Can we upgrade the package to be the latest release or a GH URL with latest code?  Linked to https://github.com/mwalmsley/galaxy-datasets/issues/16

https://github.com/mwalmsley/zoobot/blob/875f48561251ae3ae1b2664f538e709f6961bca9/setup.py#LL33C14-L33C37

**Comment by mwalmsley** [comment]
for-v1 branch now points to the new (latest) galaxy-datasets pip release.

updating master with this would break everything until v1 is merged.
