### ISSUE TITLE
Zoobot installation issues on Apple M1 Pro

### ISSUE THREAD

**Issue by igorkolesnikov13** [mwalmsley/zoobot#76]
Hi Mike,

I'm having an issue installing zoobot on my laptop.
My environment:

- OS: Ventura 13.2.1
- CPU: M1 Pro
- Python: 3.11.0

What I have done:

`mamba create -n zoobot`
`mamba activate zoobot`
`mamba install pip`
`mamba install ipykernel jupyter`
`git clone https://github.com/mwalmsley/zoobot.git`
`pip install -e "zoobot[pytorch_cpu]" --extra-index-url https://download.pytorch.org/whl/cpu`

After this, I tried importing zoobot in Jupyter Notebook with:
`from zoobot.pytorch.training import finetune`

Just for reference, here are the contents of the dirs:
`os.listdir(os.getcwd())`
Results in:
`['temp', '.DS_Store', '3_issue.ipynb', 'zoobot', '.ipynb_checkpoints']`

`os.listdir(os.getcwd()+'/zoobot')`
Results in:

`['CODE_OF_CONDUCT.md', 'zoobot.egg-info','LICENSE','requirements.txt','Dockerfile.tf','Dockerfile','CITATION.cff','pyproject.toml', 'tests', 'docker-compose-tf.yml', 'docs', 'zoobot', 'README.md', 'zoobot.code-workspace', 'results', 'only_for_me', 'setup.py',
'.dockerignore','.gitignore', 'gz_decals_data_release_analysis_demo.ipynb', '.github', 'docker-compose.yml','replication', '.git', 'data', '.readthedocs.yaml']`

**Comment by mwalmsley** [comment]
Hi Igor. I think from the commands above you did not check out the v1 branch that has the v1 code, while you followed the v1 readme instructions. I have now merged v1 to main, so I think it should work for you now - try the same commands again and let me know.

P.S
I have added zoobot[pytorch_m1] option, see the new readme. Use this instead and I think life will be good.

**Comment by igorkolesnikov13** [comment]
Hi Mike, sorry for the delay.

I tried the installation again, using the zoobot[pytorch_m1] option and got an error during the installation.
Steps:
`mamba create -n zoobot`
`mamba activate zoobot`
`mamba install pip`
`mamba install ipykernel jupyter`
`git clone https://github.com/mwalmsley/zoobot.git`
`pip install -e "zoobot[pytorch_m1]"`

Error:
`ERROR: Ignored the following versions that require a different python version: 1.21.2 Requires-Python >=3.7,<3.11; 1.21.3 Requires-Python >=3.7,<3.11; 1.21.4 Requires-Python >=3.7,<3.11; 1.21.5 Requires-Python >=3.7,<3.11; 1.21.6 Requires-Python >=3.7,<3.11; 1.6.2 Requires-Python >=3.7,<3.10; 1.6.3 Requires-Python >=3.7,<3.10; 1.7.0 Requires-Python >=3.7,<3.10; 1.7.0rc1 Requires-Python >=3.7,<3.10; 1.7.0rc2 Requires-Python >=3.7,<3.10; 1.7.1 Requires-Python >=3.7,<3.10; 1.7.2 Requires-Python >=3.7,<3.11; 1.7.3 Requires-Python >=3.7,<3.11; 1.8.0 Requires-Python >=3.8,<3.11; 1.8.0rc1 Requires-Python >=3.8,<3.11; 1.8.0rc2 Requires-Python >=3.8,<3.11; 1.8.0rc3 Requires-Python >=3.8,<3.11; 1.8.0rc4 Requires-Python >=3.8,<3.11; 1.8.1 Requires-Python >=3.8,<3.11
ERROR: Could not find a version that satisfies the requirement torch==1.12.1; extra == "pytorch_m1" (from zoobot[pytorch-m1]) (from versions: 2.0.0)
ERROR: No matching distribution found for torch==1.12.1; extra == "pytorch_m1"`

`pip install -e "zoobot[pytorch_cpu]" --extra-index-url https://download.pytorch.org/whl/cpu` `pip install -e "zoobot[tensorflow]` and  result in the same error:

`ERROR: Ignored the following versions that require a different python version: 1.21.2 Requires-Python >=3.7,<3.11; 1.21.3 Requires-Python >=3.7,<3.11; 1.21.4 Requires-Python >=3.7,<3.11; 1.21.5 Requires-Python >=3.7,<3.11; 1.21.6 Requires-Python >=3.7,<3.11; 1.6.2 Requires-Python >=3.7,<3.10; 1.6.3 Requires-Python >=3.7,<3.10; 1.7.0 Requires-Python >=3.7,<3.10; 1.7.0rc1 Requires-Python >=3.7,<3.10; 1.7.0rc2 Requires-Python >=3.7,<3.10; 1.7.1 Requires-Python >=3.7,<3.10; 1.7.2 Requires-Python >=3.7,<3.11; 1.7.3 Requires-Python >=3.7,<3.11; 1.8.0 Requires-Python >=3.8,<3.11; 1.8.0rc1 Requires-Python >=3.8,<3.11; 1.8.0rc2 Requires-Python >=3.8,<3.11; 1.8.0rc3 Requires-Python >=3.8,<3.11; 1.8.0rc4 Requires-Python >=3.8,<3.11; 1.8.1 Requires-Python >=3.8,<3.11
ERROR: Could not find a version that satisfies the requirement torch==1.12.1+cpu; extra == "pytorch_cpu" (from zoobot[pytorch-cpu]) (from versions: 2.0.0)
ERROR: No matching distribution found for torch==1.12.1+cpu; extra == "pytorch_cpu"`

`ERROR: Ignored the following versions that require a different python version: 1.21.2 Requires-Python >=3.7,<3.11; 1.21.3 Requires-Python >=3.7,<3.11; 1.21.4 Requires-Python >=3.7,<3.11; 1.21.5 Requires-Python >=3.7,<3.11; 1.21.6 Requires-Python >=3.7,<3.11; 1.6.2 Requires-Python >=3.7,<3.10; 1.6.3 Requires-Python >=3.7,<3.10; 1.7.0 Requires-Python >=3.7,<3.10; 1.7.0rc1 Requires-Python >=3.7,<3.10; 1.7.0rc2 Requires-Python >=3.7,<3.10; 1.7.1 Requires-Python >=3.7,<3.10; 1.7.2 Requires-Python >=3.7,<3.11; 1.7.3 Requires-Python >=3.7,<3.11; 1.8.0 Requires-Python >=3.8,<3.11; 1.8.0rc1 Requires-Python >=3.8,<3.11; 1.8.0rc2 Requires-Python >=3.8,<3.11; 1.8.0rc3 Requires-Python >=3.8,<3.11; 1.8.0rc4 Requires-Python >=3.8,<3.11; 1.8.1 Requires-Python >=3.8,<3.11
ERROR: Could not find a version that satisfies the requirement tensorflow==2.10.0; extra == "tensorflow" (from zoobot[tensorflow]) (from versions: none)
ERROR: No matching distribution found for tensorflow==2.10.0; extra == "tensorflow"`

**Comment by mwalmsley** [comment]
Hi @igorkolesnikov13 . The first line of the error message is: `ERROR: Ignored the following versions that require a different python version...`

Are using a version of python which is either below 3.8 or above 3.11?
