### ISSUE TITLE
Paper missing references

### ISSUE THREAD

**Issue by crhea93** [mwalmsley/zoobot#94]
Hi @mwalmsley,
 The JOSS paper is missing references. See screenshot for more detail:
![image](https://user-images.githubusercontent.com/34322936/235006869-315fc0e5-9447-42cc-b480-0452282daddd.png)

**Comment by mwalmsley** [comment]
Thank you for flagging this. I had fixed the references on the 'docs' branch that the JOSS bot uses (see [here](https://github.com/openjournals/joss-papers/blob/joss.05312/joss.05312/10.21105.joss.05312.pdf) but hadn't brought those changes into main. The PR above should fix the paper on 'main' as well.
